- name: Check if the worker join the cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: joining_if_exists_is_true
- name: Join the cluster
  shell: "{{ hostvars['k8s0']['join_command']['stdout'] }}"
  when: joining_if_exists_is_true.stat.exists != true
