- name: Check if the control plane has been initilized
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: has_been_initilized

- name: Initilize control plane
  shell: kubeadm init
  when: has_been_initilized.stat.exists != true

- name: Get join command
  shell: kubeadm token create --print-join-command
  register: join_command
