all:
  hosts:
  children:
    k8s-control-plane:
      hosts:
        k8s0: # Control plane host should be "k8s0"
          ansible_host: 10.0.2.2
          ansible_ssh_private_key_file: ~/.ssh/k8s_rsa
    k8s-worker:
      hosts:
        k8s1:
          ansible_host: 10.0.2.3
          ansible_ssh_private_key_file: ~/.ssh/k8s_rsa
        k8s2:
          ansible_host: 10.0.2.4
          ansible_ssh_private_key_file: ~/.ssh/k8s_rsa
        k8s3:
          ansible_host: 10.0.2.5
          ansible_ssh_private_key_file: ~/.ssh/k8s_rsa
    k8s-cluster:
      children:
        k8s-worker:
        k8s-control-plane:
