# Note:
# This playbook requires that
# k8s-control-plane group should be one host named k8s0.
# To join the cluster, this playbook use `kubeadm token create --print-join-command`.
# To address the output from other hosts, Ansible require host specifying
# instead of group specifying

- hosts: k8s-control-plane
  become: yes
  gather_facts: no
  tasks:
    # https://stackoverflow.com/questions/51126164/how-do-i-find-the-join-command-for-kubeadm-on-the-master
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command
        
- hosts: k8s-worker
  become: yes
  gather_facts: no
  tasks:
    - name: Check if the worker join the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: joining_if_exists_is_true

    - name: Join the cluster
      shell: "{{ hostvars['k8s0']['join_command']['stdout'] }}"
      when: joining_if_exists_is_true.stat.exists != true
